# Add ssh automatically
added_keys=`ssh-add -l`

if [ ! $(echo $added_keys | grep -o -e my_key) ]; then
    ssh-add "$HOME/.ssh/my_key"
fi

# PHP
alias php='docker run -it --rm -v $(pwd):/usr/src/myapp -w /usr/src/myapp php:cli-bullseye php'
# PHP Composer
alias composer='docker run --rm -v $(pwd):/app composer/composer'
# Laravel sail
alias sail='bash vendor/bin/sail'
# Golang
alias go='docker run -it --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:latest go'
