# PHP
alias php='docker run -it --rm -v $(pwd):/usr/src/myapp -w /usr/src/myapp php:cli-bullseye php'
# PHP Composer
alias composer='docker run --rm -v $(pwd):/app composer/composer'
# Laravel sail
alias sail='bash vendor/bin/sail'
